version: '3.1'
services:
  API:
    container_name: book-app-auth
    image: book-app-auth
    build: ./
    ports:
      - "8090:8080"
    depends_on:
      - dbauth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbauth:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  dbauth:
    image: postgres
    container_name: dbauth
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5